# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dea61dd60e19a644a89d386a19b0303f5acfcd0a9cbcf940284f318d7a2bf623610458a8394d0ec62cfbe7ef07a3557815a4375666e1ccdaaf01326909ba6f6

test:
  secret_key_base: f3758fe79125568478be643772c3a4a0eb0cb40a7d26a31d57b3e07090ee2100138b82d9c9e5334dcb7073c871cea4774dd9c53ae8031507fe126422a3be1b1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
